# Generated by Django 4.2.30 on 2026-06-15 18:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('do_number', models.CharField(max_length=100, unique=True)),
                ('do_date', models.DateField()),
                ('source', models.CharField(choices=[('NAN', 'NAN'), ('FCI', 'FCI')], max_length=10)),
                ('do_quantity_issued', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('quantity_to_be_milled', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'ordering': ['-do_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaantaParchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kaanta_parchi_no', models.CharField(max_length=100, unique=True)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_mobile_no', models.CharField(max_length=20)),
                ('gate_pass_no', models.CharField(max_length=100)),
                ('gate_pass_date', models.DateField()),
                ('no_of_boras', models.IntegerField()),
                ('weight_of_boras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('weight_of_dhan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('weight_of_empty_truck', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight_of_filled_truck', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
            ],
            options={
                'ordering': ['-gate_pass_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaantaParchiDOAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_boras', models.IntegerField()),
                ('allocated_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaanta_allocations', to='delivery_order.deliveryorder')),
                ('kaanta_parchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_allocations', to='delivery_order.kaantaparchi')),
            ],
            options={
                'unique_together': {('kaanta_parchi', 'delivery_order')},
            },
        ),
    ]
