# Generated by Django 4.2.30 on 2026-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='do_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
