# Generated by Django 4.2.30 on 2026-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=255)),
                ('bg_number', models.CharField(max_length=100, unique=True)),
                ('amount_of_bg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_issue_of_cheque', models.DateField(blank=True, null=True)),
                ('bank_name_of_cheque', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no_of_cheque', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'value'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
