# Generated by Django 4.2.30 on 2026-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankguarantee',
            old_name='account_no',
            new_name='debit_account_no',
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='bg_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='online_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='online_payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='online_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='online_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='payment_mode',
            field=models.CharField(default='cheque', max_length=20),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='pdc_account_no_of_cheque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='pdc_bank_name_of_cheque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='pdc_cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='pdc_date_of_issue_of_cheque',
            field=models.DateField(blank=True, null=True),
        ),
    ]
